name 'default_unless_test'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures default_unless_test'
long_description 'Installs/Configures default_unless_test'
version '0.1.0'
